blank_issues_enabled: true
contact_links:
  - name: Ask a question / Get support
    url: https://github.com/RahulBiju-dev/general-purpose-discord-bot/discussions
    about: Please ask questions or request support in GitHub Discussions instead of raising an issue.
